name: DevSecOps Pipeline

on: [push]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # 1. Secret Scanning
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

      # 2. Static Code Analysis
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/owasp-top-ten"

      # 3. Dependency Scan
      - name: Trivy FS Scan
        run: trivy fs --exit-code 1 --severity HIGH,CRITICAL .

      # 4. Docker Image Scan
      - name: Build Docker Image
        run: docker build -t juice-shop .
      - name: Trivy Image Scan
        run: trivy image --exit-code 1 --severity HIGH,CRITICAL juice-shop

      # 5. Dynamic App Testing
      - name: Run Juice Shop
        run: docker run -d -p 3000:3000 juice-shop
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: "http://localhost:3000"
